### ISSUE TITLE
Issue with pentaho reports and OpenERP 7

### ISSUE THREAD

**Issue by nadaerp** [WilldooIT/Pentaho-reports-for-OpenERP#107]
I've recently started using openERP 7 and I integrated the pentaho reports designer module in it... so when I create a report i get to choose whether it s a normal report or a perntaho report... and I find it in the correct place when linked to a menu item but once i try to get to it I get this error: 

OpenERP Server Error

---

Client Traceback (most recent call last):
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server\openerp\addons\web\http.py", line 204, in dispatch
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server\openerp\addons\web\controllers\main.py", line 1128, in call_kw
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server\openerp\addons\web\controllers\main.py", line 1120, in _call_kw
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server\openerp\addons\web\session.py", line 42, in proxy
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server\openerp\addons\web\session.py", line 30, in proxy_method
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server\openerp\addons\web\session.py", line 103, in send

Server Traceback (most recent call last):
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server\openerp\addons\web\session.py", line 89, in send
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server.\openerp\netsvc.py", line 292, in dispatch_rpc
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server.\openerp\service\web_services.py", line 626, in dispatch
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server.\openerp\osv\osv.py", line 190, in execute_kw
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server.\openerp\osv\osv.py", line 132, in wrapper
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server.\openerp\osv\osv.py", line 199, in execute
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server.\openerp\osv\osv.py", line 187, in execute_cr
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server\openerp\addons\pentaho_reports\wizard\report_prompt.py", line 292, in fields_view_get
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server\openerp\addons\pentaho_reports\wizard\report_prompt.py", line 207, in _setup_parameters
  File "xmlrpclib.pyc", line 1199, in __call__
  File "xmlrpclib.pyc", line 1489, in __request
  File "xmlrpclib.pyc", line 1243, in request
ProtocolError: <ProtocolError for localhost:8069/pentaho-reports-for-openerp: 404 NOT FOUND>

. so i went through system parameters and I deleted pentaho.server.url and still I got this error:

OpenERP Server Error

---

Client Traceback (most recent call last):
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server\openerp\addons\web\http.py", line 204, in dispatch
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server\openerp\addons\web\controllers\main.py", line 1128, in call_kw
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server\openerp\addons\web\controllers\main.py", line 1120, in _call_kw
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server\openerp\addons\web\session.py", line 42, in proxy
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server\openerp\addons\web\session.py", line 30, in proxy_method
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server\openerp\addons\web\session.py", line 103, in send

Server Traceback (most recent call last):
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server\openerp\addons\web\session.py", line 89, in send
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server.\openerp\netsvc.py", line 292, in dispatch_rpc
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server.\openerp\service\web_services.py", line 626, in dispatch
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server.\openerp\osv\osv.py", line 190, in execute_kw
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server.\openerp\osv\osv.py", line 132, in wrapper
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server.\openerp\osv\osv.py", line 199, in execute
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server.\openerp\osv\osv.py", line 187, in execute_cr
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server\openerp\addons\pentaho_reports\wizard\report_prompt.py", line 292, in fields_view_get
  File "C:\Program Files\OpenERP 7.0-20140310-003041\Server\server\openerp\addons\pentaho_reports\wizard\report_prompt.py", line 206, in _setup_parameters
  File "xmlrpclib.pyc", line 1463, in __init__
IOError: unsupported XML-RPC protocol

Any ideas?

**Comment by thomas-willdooit** [comment]
Hello,

The problem here seems to be that the pentaho server either isn't running, or it isn't running where the pentaho.server.url parameter was pointing. Is she running the server in tomcat? If so, you need to set that parameter to the url where you have deployed it. The deployment url is on the list in the tomcat manager application, which is normally accessed by going to http://localhost:8080/manager , assuming tomcat is running on localhost on port 8080:
![image](https://f.cloud.github.com/assets/2679141/2478596/1ebd35f8-b083-11e3-8325-763f744d3d0b.png)
So in this instance, if you are running tomcat on localhost:8080 the url would be http://localhost:8080/pentaho-reports-for-openerp .

**Comment by richard-willdooit** [comment]
@nadaerp 

I wonder if you can confirm if your problem is resolved?  We can re-open this if we hear back.

Richard
