### ISSUE TITLE
Failed to invoke method getParameterInfo

### ISSUE THREAD

**Issue by agb80** [WilldooIT/Pentaho-reports-for-OpenERP#125]
Hope you can help me, really don't understand where this error comes from. 

I generate a test report for invoice, after create the new report action when try to execute this is the error log that I get into the openerp server:

```
2014-07-09 18:47:05,098 18041 ERROR aeroo openerp.service.web_services: Exception: <Fault 0: 'Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer: null'>
Traceback (most recent call last):
  File "/home/agustin/Documents/OpenRestaurant/server/openerp/service/web_services.py", line 712, in go
    (result, format) = obj.create(cr, uid, ids, datas, context)
  File "/home/agustin/Documents/Aptana Studio 3 Workspace/openerp7/pentaho/openerp_addon/pentaho_reports/core.py", line 250, in create
    rendered_report, output_type = report_instance.execute()
  File "/home/agustin/Documents/Aptana Studio 3 Workspace/openerp7/pentaho/openerp_addon/pentaho_reports/core.py", line 193, in execute
    return self.execute_report()
  File "/home/agustin/Documents/Aptana Studio 3 Workspace/openerp7/pentaho/openerp_addon/pentaho_reports/core.py", line 210, in execute_report
    proxy_parameter_info = proxy.report.getParameterInfo(proxy_argument)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: <Fault 0: 'Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer: null'>
2014-07-09 18:47:05,128 18041 ERROR aeroo openerp.netsvc: 
(<class 'xmlrpclib.Fault'>, <Fault 0: 'Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer: null'>, <traceback object at 0x7fa2900cac68>)
Traceback (most recent call last):
  File "/home/agustin/Documents/OpenRestaurant/server/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/agustin/Documents/OpenRestaurant/server/openerp/service/web_services.py", line 654, in dispatch
    res = fn(db, uid, *params)
  File "/home/agustin/Documents/OpenRestaurant/server/openerp/service/web_services.py", line 760, in exp_report_get
    return self._check_report(report_id)
  File "/home/agustin/Documents/OpenRestaurant/server/openerp/service/web_services.py", line 738, in _check_report
    netsvc.abort_response(exc, exc.message, 'warning', exc.traceback)
  File "/home/agustin/Documents/OpenRestaurant/server/openerp/netsvc.py", line 71, in abort_response
    raise openerp.osv.osv.except_osv(description, details)
except_osv: ('', (<class 'xmlrpclib.Fault'>, <Fault 0: 'Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer: null'>, <traceback object at 0x7fa2900cac68>))
```

And a similar message I got into the java component:

```
     [java] jul 09, 2014 1:47:04 PM org.apache.xmlrpc.server.XmlRpcErrorLogger log
     [java] GRAVE: Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer: null
     [java] org.apache.xmlrpc.common.XmlRpcInvocationException: Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer: null
     [java]     at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:129)
     [java]     at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:106)
     [java]     at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:46)
     [java]     at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86)
     [java]     at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200)
     [java]     at org.apache.xmlrpc.webserver.Connection.run(Connection.java:208)
     [java]     at org.apache.xmlrpc.util.ThreadPool$Poolable$1.run(ThreadPool.java:68)
     [java] Caused by: java.lang.NullPointerException
     [java]     at com.willowit.reporting.PentahoRenderer.fixConfiguration(PentahoRenderer.java:171)
     [java]     at com.willowit.reporting.PentahoRenderer.fixConfiguration(PentahoRenderer.java:193)
     [java]     at com.willowit.reporting.PentahoRenderer.fixConfiguration(PentahoRenderer.java:193)
     [java]     at com.willowit.reporting.PentahoRenderer.getParameterInfo(PentahoRenderer.java:296)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     [java]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java]     at java.lang.reflect.Method.invoke(Method.java:606)
     [java]     at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:115)
     [java]     ... 6 more
     [java] Caused by:
     [java] java.lang.NullPointerException
     [java]     at com.willowit.reporting.PentahoRenderer.fixConfiguration(PentahoRenderer.java:171)
     [java]     at com.willowit.reporting.PentahoRenderer.fixConfiguration(PentahoRenderer.java:193)
     [java]     at com.willowit.reporting.PentahoRenderer.fixConfiguration(PentahoRenderer.java:193)
     [java]     at com.willowit.reporting.PentahoRenderer.getParameterInfo(PentahoRenderer.java:296)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     [java]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java]     at java.lang.reflect.Method.invoke(Method.java:606)
     [java]     at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:115)
     [java]     at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:106)
     [java]     at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:46)
     [java]     at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86)
     [java]     at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200)
     [java]     at org.apache.xmlrpc.webserver.Connection.run(Connection.java:208)
     [java]     at org.apache.xmlrpc.util.ThreadPool$Poolable$1.run(ThreadPool.java:68)
     [java] 
```

Initially I installed the java component downloading the precompiled war file from your server and deploy it into a Centos Server we have available for test. When that failed I tried downloading the source and compiling, got into the same situation.

Sometimes I have had hard times making java apps work in centos so go ahead and download sources and compile on my develop machine that is working with Achlinux. Got into the same situation.

Te results from java -version currently on my local machine is this one:

```
java version "1.7.0_60"
OpenJDK Runtime Environment (IcedTea 2.5.0) (Arch Linux build 7.u60_2.5.0-2-x86_64)
OpenJDK 64-Bit Server VM (build 24.60-b09, mixed mode)
```

Google around for this error but couldn't find anything.

**Comment by thomas-willdooit** [comment]
Hello @agb80 ,

`getParameterInfo` is the method on the OpenERP server that the pentaho server calls in order to populate things like dropdown lists that you have configured on your parameters. Issues such as the one you raise can be caused by a number of things. The most common is that the queries that you use to populate your parameters are returning null, which cannot be encoded into XML-RPC requests (it's not in the spec). You may need to modify these queries so that they don't return null.
