### ISSUE TITLE
pentaho report error

### ISSUE THREAD

**Issue by meilizhiwen** [WilldooIT/Pentaho-reports-for-OpenERP#129]
hey,i get problem with pentaho openerp,when i user drop down i get this problem in catalina

ERROR AbstractReportProcessor - 8871327: Report processing failed.
ERROR PdfReportUtil - Writing PDF failed.
org.pentaho.reporting.engine.classic.core.ReportParameterValidationException: The parameters provided for this report are not valid.
    at org.pentaho.reporting.engine.classic.core.states.process.ProcessState.initializeForMasterReport(ProcessState.java:187)
    at org.pentaho.reporting.engine.classic.core.layout.output.AbstractReportProcessor.prepareReportProcessing(AcatalinabstractReportProcessor.java:477)
    at org.pentaho.reporting.engine.classic.core.layout.output.AbstractReportProcessor.processReport(AbstractReportProcessor.java:1647)
    at org.pentaho.reporting.engine.classic.core.modules.output.pageable.pdf.PdfReportUtil.createPDF(PdfReportUtil.java:122)
    at com.willowit.reporting.PentahoRenderer.renderReport(Unknown Source)
    at com.willowit.reporting.PentahoRenderer.execute(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:622)
    at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:115)
    at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:106)
    at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:46)
    at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86)
    at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200)
    at org.apache.xmlrpc.webserver.XmlRpcServletServer.execute(XmlRpcServletServer.java:112)
    at org.apache.xmlrpc.webserver.XmlRpcServlet.doPost(XmlRpcServlet.java:196)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:641)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at com.willowit.application.PentahoResourceChecker.doFilter(Unknown Source)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.Abstractedness.process(AbstractHttp11Processor.java:987)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:701)
DEBUG XmlRpcStreamServer - execute: Request performed successfully
DEBUG XmlRpcStreamServer - execute: <-
Did anyone have the same problem,thank you

**Comment by meilizhiwen** [comment]
is there some problem with java in tomcat,i don't know,need someone's help, thank you .

**Comment by eddytan** [comment]
check your report parameters, try to generate without  any parameter first

**Comment by thomas-willdooit** [comment]
Hello @meilizhiwen,

The usual cause of this is having the "Validate" checkbox ticked on a parameter. Ensure it is **unticked** as below:
![image](https://cloud.githubusercontent.com/assets/2679141/3928664/32bb8c68-240e-11e4-87a3-a5d6e1d4e8f6.png)

**Comment by meilizhiwen** [comment]
@thomas-willowit,it is not fix my problem,it will give me an  empty report.

**Comment by meilizhiwen** [comment]
@edxz the parameter works in my pentaho report,when it integrate with openerp,it not work.

**Comment by richard-willdooit** [comment]
@meilizhiwen But, without the parameter, does the report work in OpenERP?  Try it with a hard coded value as the parameter result perhaps?

**Comment by meilizhiwen** [comment]
@richard-willowit  ,Thank you for your reply,without the parameter,the report works in my openerp.but i think i need  the parameter to do more job.how to do a hard coded value as the parameter result?

**Comment by meilizhiwen** [comment]
thanks.I fix it

**Comment by eddytan** [comment]
@meilizhiwen hi meilizhiwen,
can you please explain how did you fix it ?
thx before

**Comment by meilizhiwen** [comment]
@edxz,hi,dear edxz, first i change the java version,i update it.but i found it not work,then i change the pentaho-reports-for-openerp version,then it works.

**Comment by eddytan** [comment]
@meilizhiwen which version did you use ?
thx for the information, it may be a clue for my issue as well, haha

**Comment by meilizhiwen** [comment]
@edxz my version is 61.the first use is 60.also need to deploy it in tomcat
