### ISSUE TITLE
Failed to invoke method execute in class com.willowit.reporting.PentahoRenderer: Failed to read server's response: Connection refused"

### ISSUE THREAD

**Issue by iw3hxn** [WilldooIT/Pentaho-reports-for-OpenERP#185]
Hello, i installed Pentaho-reports-for-OpenERP on an Odoo Server and the war file application on tomcat 7 server (in a different machine) 

when i print a report (simple report of a blank A4 page connect to res.partner) i get this error:
on odoo log:

Fault: <Fault 0: "Failed to invoke method execute in class com.willowit.reporting.PentahoRenderer: Failed to read server's response: Connection refused">
2014-12-17 11:32:09,296 24400 ERROR cse openerp.addons.web.controllers.main: An exception occured during an http request

and on tomcat log:

Caused by: org.apache.xmlrpc.XmlRpcException: Failed to read server's response: Connection refused
        at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:161)
        at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
        at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
        at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:137)
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:126)
        at com.debortoliwines.openerp.api.Session.startSession(Session.java:127)
        at com.debortoliwines.openerp.reporting.di.OpenERPHelper.getSession(OpenERPHelper.java:401)
        at com.debortoliwines.openerp.reporting.di.OpenERPHelper.getData(OpenERPHelper.java:86)
        at org.pentaho.reporting.engine.classic.extensions.datasources.openerp.OpenERPDataFactory.queryData(OpenERPDataFactory.java:197)

any idea?

**Comment by iw3hxn** [comment]
i setup tomcat  on same server of Odoo, and work
