### ISSUE TITLE
Object request failed in production

### ISSUE THREAD

**Issue by flotho** [WilldooIT/Pentaho-reports-for-OpenERP#193]
Hy,

I'm working on a specific report with an object request.
Here is the error message :

```
2015-02-23 15:01:05,373 12673 WARNING at_prod openerp.osv.osv: SERIALIZATION_FAILURE, maximum number of tries reached
2015-02-23 15:01:05,375 12673 ERROR at_prod openerp.netsvc: ERREUR:  n'a pas pu sérialiser un accès à cause d'une mise à jour en parallèle
CONTEXTE : instruction SQL « SELECT 1 FROM ONLY "public"."res_users" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR SHARE OF x »
Traceback (most recent call last):
  File "/home/openerp/odoo-V7/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/openerp/odoo-V7/openerp/service/web_services.py", line 632, in dispatch
    res = fn(db, uid, *params)
  File "/home/openerp/odoo-V7/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/home/openerp/odoo-V7/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/home/openerp/odoo-V7/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/home/openerp/odoo-V7/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/home/openerp/odoo-V7/openerp/osv/orm.py", line 4571, in create
    cr.execute('insert into "'+self._table+'" (id'+upd0+") values ("+str(id_new)+upd1+')', tuple(upd2))
  File "/home/openerp/odoo-V7/openerp/sql_db.py", line 161, in wrapper
    return f(self, *args, **kwargs)
  File "/home/openerp/odoo-V7/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: ERREUR:  n'a pas pu sérialiser un accès à cause d'une mise à jour en parallèle
CONTEXTE : instruction SQL « SELECT 1 FROM ONLY "public"."res_users" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR SHARE OF x »

```

I tried the same report on a local database with the same datas and it failed. Is there any tips for avoiding this?
Regards

**Comment by richard-willdooit** [comment]
Ahh, a lot of effort has gone in to trying to avoid the serialisation problems in object reporting, for version 8.  In version 7, the efforts have been a little more random.

The issue arises because the report itself has to "sign in", when it is object based.  Now, if the calling code needs to write information on the res_user file as well, then the whole thing gets in a twisted knot.

This was particularly a problem for emailed reports - and the willow_pentaho_email_patch in the version 7 repo was generally successful in that situation.

However, I think something changed in the version 7 code base in the last 3-6 months.  Because, we too had a client who had Pentaho reports running successfully, and after pulling the latest openerp 7 in December or January for them (it had not been updated for quite a while), started getting that serialization problem.

We did a brute force, "not entirely correct for all situations, but works for them" fix directly on their code which we did not push back to here.  But it is in the email patch.  Is that where you are experiencing the problem?  If so, here is the nasty band-aid patch...

```
diff --git a/openerp_addon/willow_pentaho_email_patch/email_template.py b/openerp_addon/willow_pentaho_email_pa
index a6170d1..719e6cc 100644
--- a/openerp_addon/willow_pentaho_email_patch/email_template.py
+++ b/openerp_addon/willow_pentaho_email_patch/email_template.py
@@ -83,13 +83,14 @@ class email_template_patch(osv.osv):
                 if existing_uids:
                     self._unlink_user_and_partner(crtemp, SUPERUSER_ID, existing_uids, context=ctx)

+                cr.commit() # The following section another cursor to do some writing on the partner, but we a
                 new_uid = user_obj.copy(crtemp, SUPERUSER_ID, uid, default={'employee_ids': False,
                                                                             'message_ids': False,
-                                                                            'name': user.name}, context=ctx)
+                                                                            'name': user.name,
+                                                                            'partner_id':None}, context=ctx)
+                user_obj.write(crtemp,SUPERUSER_ID,uid,{"partner_id":user.partner_id.id},context=ctx)
                 crtemp.commit()
-
                 service = netsvc.LocalService(report_service)
-                cr.commit() # The following line uses another cursor to do some writing on the partner, but wediff --git a/openerp_addon/willow_pentaho_email_patch/email_template.py b/openerp_addon/willow_pentaho_email_pa
index a6170d1..719e6cc 100644
--- a/openerp_addon/willow_pentaho_email_patch/email_template.py
+++ b/openerp_addon/willow_pentaho_email_patch/email_template.py
@@ -83,13 +83,14 @@ class email_template_patch(osv.osv):
                 if existing_uids:
                     self._unlink_user_and_partner(crtemp, SUPERUSER_ID, existing_uids, context=ctx)

+                cr.commit() # The following section another cursor to do some writing on the partner, but we a
                 new_uid = user_obj.copy(crtemp, SUPERUSER_ID, uid, default={'employee_ids': False,
                                                                             'message_ids': False,
-                                                                            'name': user.name}, context=ctx)
+                                                                            'name': user.name,
+                                                                            'partner_id':None}, context=ctx)
+                user_obj.write(crtemp,SUPERUSER_ID,uid,{"partner_id":user.partner_id.id},context=ctx)
                 crtemp.commit()
-
                 service = netsvc.LocalService(report_service)
-                cr.commit() # The following line uses another cursor to do some writing on the partner, but we
                 (result, format) = service.create(crtemp, new_uid, [res_id], {'model': template.model}, ctx)
                 crtemp.commit()
                 crtemp.close()
```

**Comment by flotho** [comment]
Hy,

I precised that the problem is coming from report that has it's own menu.
I have multiple parameters and queries inside and one of them is in object. 
Once I did it in sql, the problem disappears.
I'll try your patch ASAP.
regards

**Comment by flotho** [comment]
@richard-willowit I precise that the user that execute the report has a ldap based account. Maybe this could explain some issues?
