### ISSUE TITLE
Failed to invoke method getParameterInfo

### ISSUE THREAD

**Issue by aitorbouzas** [WilldooIT/Pentaho-reports-for-OpenERP#203]
Hello,

Just had the error shown in the title of the issue after a new fresh installation of Pentaho module on OpenERP and the war (pentaho-reports-for-openerp) into an Apache Tomcat 7 server...

I have the OpenERP 8 installed into a Bitnami server (Ubuntu 14.04 Server). Then I installed into it the Apache Tomcat 7 and deployed your war file. After that I installed the OpenERP module (your version 80) into the server, and made a testing report in the Pentaho Report Designer in my local Windows with just the company name of an invoice. I used the OpenERP Data Access method for getting fields from de PostgreSQL database...

This is the complete error from the OpenERP log: 

2015-03-30 08:16:09,209 20675 ERROR openerp_masterled openerp.service.report: Exception: <Fault 0: 'Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer: Unable to parse the document: ResourceKey{schema=org.pentaho.reporting.libraries.docbundle.bundleloader.ZipResourceBundleLoader, identifier=content.xml, factoryParameters={org.pentaho.reporting.libraries.resourceloader.FactoryParameterKey{name=repository}=org.pentaho.reporting.libraries.repository.zipreader.ZipReadRepository@3d9800b8, org.pentaho.reporting.libraries.resourceloader.FactoryParameterKey{name=repository-loader}=org.pentaho.reporting.libraries.docbundle.bundleloader.ZipResourceBundleLoader@407a52e4}, parent=ResourceKey{schema=org.pentaho.reporting.libraries.resourceloader.loader.raw.RawResourceLoader, identifier=[B@797a1386, factoryParameters={}, parent=null}}'>
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/service/report.py", line 93, in go
    result, format = openerp.report.render_report(cr, uid, ids, object, datas, context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/report/**init**.py", line 40, in render_report
    return registry['ir.actions.report.xml'].render_report(cr, uid, ids, name, data, context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/addons/base/ir/ir_actions.py", line 155, in render_report
    return new_report.create(cr, uid, res_ids, data, context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/addons/pentaho_reports/core.py", line 258, in create
    rendered_report, output_type = report_instance.execute()
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/addons/pentaho_reports/core.py", line 199, in execute
    return self.execute_report()
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/addons/pentaho_reports/core.py", line 216, in execute_report
    proxy_parameter_info = proxy.report.getParameterInfo(proxy_argument)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.__send(self.__name, args)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(*_self._stack[0])
Fault: <Fault 0: 'Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer: Unable to parse the document: ResourceKey{schema=org.pentaho.reporting.libraries.docbundle.bundleloader.ZipResourceBundleLoader, identifier=content.xml, factoryParameters={org.pentaho.reporting.libraries.resourceloader.FactoryParameterKey{name=repository}=org.pentaho.reporting.libraries.repository.zipreader.ZipReadRepository@3d9800b8, org.pentaho.reporting.libraries.resourceloader.FactoryParameterKey{name=repository-loader}=org.pentaho.reporting.libraries.docbundle.bundleloader.ZipResourceBundleLoader@407a52e4}, parent=ResourceKey{schema=org.pentaho.reporting.libraries.resourceloader.loader.raw.RawResourceLoader, identifier=[B@797a1386, factoryParameters={}, parent=null}}'>
2015-03-30 08:16:09,414 20675 ERROR openerp_masterled openerp.addons.web.controllers.main: An exception occured during an http request
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/addons/web/controllers/main.py", line 69, in wrap
    return f(_args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/addons/web/controllers/main.py", line 1577, in index
    request.session.db, request.session.uid, request.session.password, report_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/http.py", line 828, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/http.py", line 108, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/service/report.py", line 34, in dispatch
    res = fn(db, uid, *params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/service/report.py", line 141, in exp_report_get
    return _check_report(report_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/service/report.py", line 119, in _check_report
    raise openerp.osv.orm.except_orm(exc.message, exc.traceback)
except_orm: ('', (<class 'xmlrpclib.Fault'>, <Fault 0: 'Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer: Unable to parse the document: ResourceKey{schema=org.pentaho.reporting.libraries.docbundle.bundleloader.ZipResourceBundleLoader, identifier=content.xml, factoryParameters={org.pentaho.reporting.libraries.resourceloader.FactoryParameterKey{name=repository}=org.pentaho.reporting.libraries.repository.zipreader.ZipReadRepository@3d9800b8, org.pentaho.reporting.libraries.resourceloader.FactoryParameterKey{name=repository-loader}=org.pentaho.reporting.libraries.docbundle.bundleloader.ZipResourceBundleLoader@407a52e4}, parent=ResourceKey{schema=org.pentaho.reporting.libraries.resourceloader.loader.raw.RawResourceLoader, identifier=[B@797a1386, factoryParameters={}, parent=null}}'>, <traceback object at 0x7faac437e128>))

Thanks in advice

**Comment by aitorbouzas** [comment]
I just saw issue #201 so... Will try with an older version of Pentaho Report Designer... Will reply soon.

**Comment by aitorbouzas** [comment]
Just tried an older version of Pentaho Report Designer, now I get another error...

I checked several times my system parameters settings for Pentaho, all are set with localhost and with the proper users and passwords... Can someone help me?

2015-03-30 08:16:09,209 20675 ERROR openerp_masterled openerp.service.report: Exception: <Fault 0: 'Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer: Unable to parse the document: ResourceKey{schema=org.pentaho.reporting.libraries.docbundle.bundleloader.ZipResourceBundleLoader, identifier=content.xml, factoryParameters={org.pentaho.reporting.libraries.resourceloader.FactoryParameterKey{name=repository}=org.pentaho.reporting.libraries.repository.zipreader.ZipReadRepository@3d9800b8, org.pentaho.reporting.libraries.resourceloader.FactoryParameterKey{name=repository-loader}=org.pentaho.reporting.libraries.docbundle.bundleloader.ZipResourceBundleLoader@407a52e4}, parent=ResourceKey{schema=org.pentaho.reporting.libraries.resourceloader.loader.raw.RawResourceLoader, identifier=[B@797a1386, factoryParameters={}, parent=null}}'>
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/service/report.py", line 93, in go
    result, format = openerp.report.render_report(cr, uid, ids, object, datas, context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/report/**init**.py", line 40, in render_report
    return registry['ir.actions.report.xml'].render_report(cr, uid, ids, name, data, context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/addons/base/ir/ir_actions.py", line 155, in render_report
    return new_report.create(cr, uid, res_ids, data, context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/addons/pentaho_reports/core.py", line 258, in create
    rendered_report, output_type = report_instance.execute()
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/addons/pentaho_reports/core.py", line 199, in execute
    return self.execute_report()
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/addons/pentaho_reports/core.py", line 216, in execute_report
    proxy_parameter_info = proxy.report.getParameterInfo(proxy_argument)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.__send(self.__name, args)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(*_self._stack[0])
Fault: <Fault 0: 'Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer: Unable to parse the document: ResourceKey{schema=org.pentaho.reporting.libraries.docbundle.bundleloader.ZipResourceBundleLoader, identifier=content.xml, factoryParameters={org.pentaho.reporting.libraries.resourceloader.FactoryParameterKey{name=repository}=org.pentaho.reporting.libraries.repository.zipreader.ZipReadRepository@3d9800b8, org.pentaho.reporting.libraries.resourceloader.FactoryParameterKey{name=repository-loader}=org.pentaho.reporting.libraries.docbundle.bundleloader.ZipResourceBundleLoader@407a52e4}, parent=ResourceKey{schema=org.pentaho.reporting.libraries.resourceloader.loader.raw.RawResourceLoader, identifier=[B@797a1386, factoryParameters={}, parent=null}}'>
2015-03-30 08:16:09,414 20675 ERROR openerp_masterled openerp.addons.web.controllers.main: An exception occured during an http request
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/addons/web/controllers/main.py", line 69, in wrap
    return f(_args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/addons/web/controllers/main.py", line 1577, in index
    request.session.db, request.session.uid, request.session.password, report_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/http.py", line 828, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/http.py", line 108, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/service/report.py", line 34, in dispatch
    res = fn(db, uid, *params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/service/report.py", line 141, in exp_report_get
    return _check_report(report_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/service/report.py", line 119, in _check_report
    raise openerp.osv.orm.except_orm(exc.message, exc.traceback)
except_orm: ('', (<class 'xmlrpclib.Fault'>, <Fault 0: 'Failed to invoke method getParameterInfo in class com.willowit.reporting.PentahoRenderer: Unable to parse the document: ResourceKey{schema=org.pentaho.reporting.libraries.docbundle.bundleloader.ZipResourceBundleLoader, identifier=content.xml, factoryParameters={org.pentaho.reporting.libraries.resourceloader.FactoryParameterKey{name=repository}=org.pentaho.reporting.libraries.repository.zipreader.ZipReadRepository@3d9800b8, org.pentaho.reporting.libraries.resourceloader.FactoryParameterKey{name=repository-loader}=org.pentaho.reporting.libraries.docbundle.bundleloader.ZipResourceBundleLoader@407a52e4}, parent=ResourceKey{schema=org.pentaho.reporting.libraries.resourceloader.loader.raw.RawResourceLoader, identifier=[B@797a1386, factoryParameters={}, parent=null}}'>, <traceback object at 0x7faac437e128>))

**Comment by aitorbouzas** [comment]
Just had it! "localhost" was not a good value for pentaho.xmlrpc.interface because in openerp-server.conf it was set to an IP (192.168.11.106). Just modified the system parameter to give it this IP and worked perfectly

Solutions for my issue:
1. Use Pentaho Report Designer 5.0.1 instead of 5.3
2. Configure the xmlrpc in openerp-server.conf (setting it to True with an interface an a port)
3. Set the parameters settings into OpenERP with the values used for openerp-server.conf in order to get the object-based report to work.

Thanks!

**Comment by richard-willdooit** [comment]
@Softdil Just tested the latest build and all good.  war file updated appropriately, too.

**Comment by mad-odoo** [comment]
Hello,
I am having some issue similar to when invoking getParameterInfo.
When I am trying to generate a pentaho report form odoo, facing some bug as described below:

`2016-04-01 13:19:26,168 12710 ERROR pentaho_reports openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/weboffice/workspace/odoo/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/weboffice/workspace/odoo/openerp/http.py", line 576, in dispatch
    result = self._call_function(**self.params)
  File "/home/weboffice/workspace/odoo/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/weboffice/workspace/odoo/openerp/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/weboffice/workspace/odoo/openerp/http.py", line 309, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/weboffice/workspace/odoo/openerp/http.py", line 805, in __call__
    return self.method(*args, **kw)
  File "/home/weboffice/workspace/odoo/openerp/http.py", line 405, in response_wrap
    response = f(*args, **kw)
  File "/home/weboffice/workspace/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/weboffice/workspace/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/weboffice/workspace/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/weboffice/workspace/odoo/pentaho_reports/openerp_addon/pentaho_reports/wizard/report_prompt.py", line 365, in fields_view_get
    parameters = self._setup_parameters(cr, uid, report_action_id, context=context)
  File "/home/weboffice/workspace/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/weboffice/workspace/odoo/pentaho_reports/openerp_addon/pentaho_reports/wizard/report_prompt.py", line 201, in _setup_parameters
    report_parameters = proxy.report.getParameterInfo(proxy_argument)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1321, in single_request
    response.msg,
ProtocolError: <ProtocolError for 192.168.99.133:8080/pentaho: 302 Found>`

I am using pentaho_reports module with odoo v8.0 . Also I have configured my system parameter properly as described below: 
pentaho.server.url: **http://192.168.99.133:8080/pentaho**
pentaho.openerp.xml.interface: **True**
pentaho.openerp.xml.port: **8088**
pentaho.postgres.host: **192.168.99.133**
pentaho.postgres.port: **5432**
pentaho.postgres.login: **openerp**
pentaho.postgres.password: **openerp**

I am sure about the system paramenters.
I am using PRD 6.0.1.0 and pentaho BI server 6.0.1.0
I am using same PC for both odoo and pentaho server.

@Softdil, @richard-willowit  Please share your idea about this issue.
Let me know if what i am missing anything or you need more detail of issue.
Thanks in advance

**Comment by quangdangfit** [comment]
I have same issue when deploy on odoo 11, any help?

**Comment by richard-willdooit** [comment]
@QuangPhuocDang 
Just remember, the error is very generic.  You really need to examine the tomcat error file.  Also, note there are a number of git issues here tagged with this error: [here](https://github.com/WilldooIT/Pentaho-reports-for-OpenERP/issues?q=label%3A%22Failed+to+invoke+method+getParameterInfo%22+is%3Aclosed)
