### ISSUE TITLE
AttributeError: 'ir.actions.report.xml' object has no attribute 'behaviour'

### ISSUE THREAD

**Issue by disna-sistemas** [WilldooIT/Pentaho-reports-for-OpenERP#210]
I have followed all the steps but when I try to render my report, a very simple one linked to account.invoice model, I get this traceback:

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 69, in wrap
    return f(_args, *_kwargs)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 1574, in index
    request.session.db, request.session.uid, request.session.password, report_id)
  File "/opt/odoo/v8/core/openerp/http.py", line 872, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/odoo/v8/core/openerp/http.py", line 114, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/v8/core/openerp/service/report.py", line 34, in dispatch
    res = fn(db, uid, *params)
  File "/opt/odoo/v8/other-addons/base_report_to_printer/report_service.py", line 58, in exp_report_get
    data = report.behaviour()[report.id]
AttributeError: 'ir.actions.report.xml' object has no attribute 'behaviour'

I updated the core some days ago.

Any idea ?

Thank you very much

**Comment by flotho** [comment]
Hy,

It looks like the field behaviour is no longer part of your model. Could you have a look in Odoo > Settings > ... > Models , get your model and check whether the behaviour field is present.

Regards

**Comment by disna-sistemas** [comment]
I solved the issue by installing a module named base_report_to_printer.  This module extends ir.actions.report.xml model adding a function called behaviour.

Regards

**Comment by flotho** [comment]
you're welcome
