### ISSUE TITLE
pentaho.auth.crypt create report error

### ISSUE THREAD

**Issue by marek-vavricka** [WilldooIT/Pentaho-reports-for-OpenERP#237]
Hi,

when trying to print a pentaho based report, following error appears. Printing reports works for admin, but not for the other users.

Temporary fix - Add Pentaho Auth Crypt to ACL manually.

Thanks for help!

2015-12-16 15:56:45,956 20808 WARNING xxxx openerp.addons.base.ir.ir_model: Access Denied by ACLs for operation: create, uid: 3, model: pentaho.auth.crypt
2015-12-16 15:56:45,957 20808 ERROR xxxx openerp.service.report: Exception: ('AccessError', u'Sorry, you are not allowed to create this kind of document. (Document model: pentaho.auth.crypt)')
Traceback (most recent call last):
  File "/data/erp8/openerp/service/report.py", line 93, in go
    result, format = openerp.report.render_report(cr, uid, ids, object, datas, context)
  File "/data/erp8/openerp/report/**init**.py", line 40, in render_report
    return registry['ir.actions.report.xml'].render_report(cr, uid, ids, name, data, context)
  File "/data/erp8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/data/erp8/openerp/addons/base/ir/ir_actions.py", line 155, in render_report
    return new_report.create(cr, uid, res_ids, data, context)
  File "/data/erp8/addons/pentaho_reports/core.py", line 261, in create
    rendered_report, output_type = report_instance.execute()
  File "/data/erp8/addons/pentaho_reports/core.py", line 201, in execute
    return self.execute_report()
  File "/data/erp8/addons/pentaho_reports/core.py", line 219, in execute_report
    proxy_url, proxy_argument = get_proxy_args(self, self.cr, self.uid, self.prpt_content, self.context_vars)
  File "/data/erp8/addons/pentaho_reports/core.py", line 141, in get_proxy_args
    password_to_use = pool.get('res.users').pentaho_pass_token(cr, uid, uid)
  File "/data/erp8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/data/erp8/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/data/erp8/addons/pentaho_reports/core_newapi.py", line 20, in pentaho_pass_token
    return '%s%s' % (SKIP_DATE, self.decide_on_password())
  File "/data/erp8/addons/pentaho_reports_auth_crypt/pentaho_auth_crypt.py", line 20, in decide_on_password
    return self.create_temporary_password_pentaho()
  File "/data/erp8/addons/pentaho_reports_auth_crypt/pentaho_auth_crypt.py", line 32, in create_temporary_password_pentaho
    'timestamp': datetime.now().strftime(DEFAULT_SERVER_DATETIME_FORMAT),
  File "/data/erp8/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/data/erp8/openerp/models.py", line 4061, in create
    self.check_access_rights('create')
  File "/data/erp8/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/data/erp8/openerp/api.py", line 451, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/data/erp8/openerp/models.py", line 3496, in check_access_rights
    return self.pool.get('ir.model.access').check(cr, uid, self._name, operation, raise_exception)
  File "/data/erp8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "<string>", line 2, in check
  File "/data/erp8/openerp/tools/cache.py", line 122, in lookup
    value = d[key] = self.method(_args, *_kwargs)
  File "/data/erp8/openerp/addons/base/ir/ir_model.py", line 800, in check
    raise openerp.exceptions.AccessError(msg % msg_params)
AccessError: ('AccessError', u'Sorry, you are not allowed to create this kind of document. (Document model: pentaho.auth.crypt)')

**Comment by richard-willdooit** [comment]
@marek-vavricka Sorry about the delay in responding.  This has been addressed in a pull request adding the security.  Thanks.
