### ISSUE TITLE
Error Installing Pentaho Module  -  Odoo Server Error

### ISSUE THREAD

**Issue by pinjisi** [WilldooIT/Pentaho-reports-for-OpenERP#238]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server.\openerp\http.py", line 536, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server.\openerp\http.py", line 573, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server.\openerp\http.py", line 309, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server.\openerp\http.py", line 306, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server.\openerp\http.py", line 802, in __call__
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server.\openerp\http.py", line 402, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server\openerp\addons\web\controllers\main.py", line 941, in call_button
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server\openerp\addons\web\controllers\main.py", line 929, in _call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server\openerp\addons\base\module\module.py", line 450, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server\openerp\addons\base\module\module.py", line 498, in _button_immediate_function
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server.\openerp\modules\registry.py", line 370, in new
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server.\openerp\modules\loading.py", line 355, in load_modules
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server.\openerp\modules\loading.py", line 255, in load_marked_modules
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server.\openerp\modules\loading.py", line 152, in load_module_graph
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server.\openerp\modules\registry.py", line 163, in load
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server.\openerp\models.py", line 645, in _build_model
  File "C:\Program Files (x86)\Odoo 8.0-20150601\server\openerp\addons\pentaho_reports\ui.py", line 23, in __init__
TypeError: 'NoneType' object has no attribute '**getitem**'

**Comment by richard-willdooit** [comment]
@pinjisi Sorry about the delay in getting to these issues - have you resolved the error?

**Comment by pinjisi** [comment]
Yes, I do not have Pentaho problems at the moment.  I just wish I
could be the Pentaho Partner in Botswana and Zimbabwe

**Comment by pinjisi** [comment]
Thank You
