### ISSUE TITLE
Using Odoo 8 and Pentaho with Docker 

### ISSUE THREAD

**Issue by eqms** [WilldooIT/Pentaho-reports-for-OpenERP#240]
Hi,

I just builded your docker images on my server.
I used https://github.com/trabacus-softapps/docker-wildfly for this.
The container is running well.

But if I try to open a report from my Odoo Docker instance I will get an error:

016-01-28 18:42:30,079 17 ERROR beh openerp.service.report: Exception: 
Traceback (most recent call last):
File "/opt/odoo/odoo-server/openerp/service/report.py", line 93, in go
result, format = openerp.report.render_report(cr, uid, ids, object, datas, context)
File "/opt/odoo/odoo-server/openerp/report/init.py", line 40, in render_report
return registry['ir.actions.report.xml'].render_report(cr, uid, ids, name, data, context)
File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
return old_api(self, args, _kwargs)
File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_actions.py", line 156, in render_report
return new_report.create(cr, uid, res_ids, data, context)
File "/opt/odoo/odoo-server/addons/pentaho_reports/core.py", line 261, in create
rendered_report, output_type = report_instance.execute()
File "/opt/odoo/odoo-server/addons/pentaho_reports/core.py", line 201, in execute
return self.execute_report()
File "/opt/odoo/odoo-server/addons/pentaho_reports/core.py", line 239, in execute_report
rendered_report = proxy.report.execute(proxy_argument).data
File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in call
return self.__send(self.__name, args)
File "/usr/lib/python2.7/xmlrpclib.py", line 1591, in __request
verbose=self.__verbose
File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
return self.single_request(host, handler, request_body, verbose)
File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
return self.parse_response(response)
File "/usr/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
return u.close()
File "/usr/lib/python2.7/xmlrpclib.py", line 794, in close
raise Fault(_self._stack[0])
Fault: 
2016-01-28 18:42:30,237 17 ERROR beh openerp.addons.web.controllers.main: An exception occured during an http request
Traceback (most recent call last):
File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 70, in wrap
return f(args, **kwargs)
File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 1576, in index
request.session.db, request.session.uid, request.session.password, report_id)
File "/opt/odoo/odoo-server/openerp/http.py", line 879, in proxy_method
result = dispatch_rpc(self.service_name, method, args)
File "/opt/odoo/odoo-server/openerp/http.py", line 115, in dispatch_rpc
result = dispatch(method, params)
File "/opt/odoo/odoo-server/openerp/service/report.py", line 34, in dispatch
res = fn(db, uid, *params)
File "/opt/odoo/odoo-server/openerp/service/report.py", line 141, in exp_report_get
return _check_report(report_id)
File "/opt/odoo/odoo-server/openerp/service/report.py", line 119, in _check_report
raise openerp.osv.orm.except_orm(exc.message, exc.traceback)
except_orm: ('', (, , ))

**Comment by richard-willdooit** [comment]
@eqms I am unfamiliar with using Docker.  As far as I can see from the trace log, it is calling execute, which goes down through the chain, and ultimately calls the proxied action.  This is not working, implying that pentaho is not running in a way that makes it available to the Docker environment.  I don't know if that environment can talk to Tomcat?

"proxy.report.execute(proxy_argument).data" is where the digging would need to begin, but I really cannot give many pointers...

**Comment by richard-willdooit** [comment]
@eqms See #248
