### ISSUE TITLE
Failed to invoke method getParameterInfo: ProtocolError 

### ISSUE THREAD

**Issue by mad-odoo** [WilldooIT/Pentaho-reports-for-OpenERP#255]
Hello @richard-willowit ,
Hope you doing well.

I am having some issue similar to when invoking getParameterInfo.
When I am trying to generate a pentaho report form odoo, facing some bug as described below:

2016-04-01 13:19:26,168 12710 ERROR pentaho_reports openerp.http: Exception during JSON request handling. Traceback (most recent call last): File "/home/weboffice/workspace/odoo/openerp/http.py", line 539, in _handle_exception return super(JsonRequest, self)._handle_exception(exception) File "/home/weboffice/workspace/odoo/openerp/http.py", line 576, in dispatch result = self._call_function(*_self.params) File "/home/weboffice/workspace/odoo/openerp/http.py", line 312, in _call_function return checked_call(self.db, *args, *_kwargs) File "/home/weboffice/workspace/odoo/openerp/service/model.py", line 119, in wrapper return f(dbname, _args, *_kwargs) File "/home/weboffice/workspace/odoo/openerp/http.py", line 309, in checked_call return self.endpoint(_a, *_kw) File "/home/weboffice/workspace/odoo/openerp/http.py", line 805, in __call__ return self.method(_args, *_kw) File "/home/weboffice/workspace/odoo/openerp/http.py", line 405, in response_wrap response = f(_args, *_kw) File "/home/weboffice/workspace/odoo/addons/web/controllers/main.py", line 944, in call_kw return self._call_kw(model, method, args, kwargs) File "/home/weboffice/workspace/odoo/addons/web/controllers/main.py", line 936, in _call_kw return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs) File "/home/weboffice/workspace/odoo/openerp/api.py", line 268, in wrapper return old_api(self, _args, *_kwargs) File "/home/weboffice/workspace/odoo/pentaho_reports/openerp_addon/pentaho_reports/wizard/report_prompt.py", line 365, in fields_view_get parameters = self._setup_parameters(cr, uid, report_action_id, context=context) File "/home/weboffice/workspace/odoo/openerp/api.py", line 268, in wrapper return old_api(self, _args, *_kwargs) File "/home/weboffice/workspace/odoo/pentaho_reports/openerp_addon/pentaho_reports/wizard/report_prompt.py", line 201, in _setup_parameters report_parameters = proxy.report.getParameterInfo(proxy_argument) File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__ return self.__send(self.__name, args) File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request verbose=self.__verbose File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request return self.single_request(host, handler, request_body, verbose) File "/usr/lib/python2.7/xmlrpclib.py", line 1321, in single_request response.msg, ProtocolError: <ProtocolError for 192.168.99.133:8080/pentaho: 302 Found>

I am using pentaho_reports module with odoo v8.0 . Also I have configured my system parameter properly as described below: 
pentaho.server.url: http://192.168.99.133:8080/pentaho
pentaho.openerp.xml.interface: True
pentaho.openerp.xml.port: 8088
pentaho.postgres.host: 192.168.99.133
pentaho.postgres.port: 5432
pentaho.postgres.login: openerp
pentaho.postgres.password: openerp

I am sure about the system paramenters.
I am using PRD 6.0.1.0 and pentaho BI server 6.0.1.0
I am using same PC for both odoo and pentaho server.

Please share your idea about this issue.
Let me know if what i am missing anything or you need more detail of issue.
Thanks in advance

**Comment by richard-willdooit** [comment]
Without picking things apart yet:

A) You ususually do not need to configure the xml interface and port, but the interface should either be the hostname of the xml interface.  If you do not configure either of these, it will pick them up from the openerp.conf file, which would rarely be the wrong values.

B) We have not done any testing beyond version 5.4.  6 is still to be looked at.

But, first change or clear the xml interface setting

**Comment by mad-odoo** [comment]
@richard-willowit 
Thanks for your valuable response. 
As you told, i will clear xml interface and will try with older version of PRD and BI server. And will let you know.

**Comment by mad-odoo** [comment]
Hello,

I reset xml interface settings and now using version 5.3.0 for both PRD and BI server. 
still getting error below:

`2016-04-05 11:08:28,701 4455 WARNING pentaho openerp.pooler: openerp.pooler.get_db_and_pool() is deprecated.
2016-04-05 11:08:28,741 4455 ERROR pentaho openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/weboffice/workspace/odoo/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/weboffice/workspace/odoo/openerp/http.py", line 576, in dispatch
    result = self._call_function(**self.params)
  File "/home/weboffice/workspace/odoo/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/weboffice/workspace/odoo/openerp/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/weboffice/workspace/odoo/openerp/http.py", line 309, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/weboffice/workspace/odoo/openerp/http.py", line 805, in __call__
    return self.method(*args, **kw)
  File "/home/weboffice/workspace/odoo/openerp/http.py", line 405, in response_wrap
    response = f(*args, **kw)
  File "/home/weboffice/workspace/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/weboffice/workspace/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/weboffice/workspace/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/weboffice/workspace/odoo/pentaho_reports/openerp_addon/pentaho_reports/wizard/report_prompt.py", line 365, in fields_view_get
    parameters = self._setup_parameters(cr, uid, report_action_id, context=context)
  File "/home/weboffice/workspace/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/weboffice/workspace/odoo/pentaho_reports/openerp_addon/pentaho_reports/wizard/report_prompt.py", line 201, in _setup_parameters
    report_parameters = proxy.report.getParameterInfo(proxy_argument)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1321, in single_request
    response.msg,
ProtocolError: <ProtocolError for localhost:8080/pentaho: 302 Found>
`

server is running on http://localhost:8080/pentaho.
I conformed that.

**Comment by mad-odoo** [comment]
The issue fixed with PRD 5.3
