### ISSUE TITLE
Issue in installing Pentaho Reports for OpenERP

### ISSUE THREAD

**Issue by ravindragullapalli** [WilldooIT/Pentaho-reports-for-OpenERP#278]
Getting below error

> Traceback (most recent call last):
>   File "/odoo/odoo-server/openerp/http.py", line 544, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/odoo/odoo-server/openerp/http.py", line 581, in dispatch
>     result = self._call_function(*_self.params)
>   File "/odoo/odoo-server/openerp/http.py", line 317, in _call_function
>     return checked_call(self.db, *args, *_kwargs)
>   File "/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
>     return f(dbname, _args, *_kwargs)
>   File "/odoo/odoo-server/openerp/http.py", line 314, in checked_call
>     return self.endpoint(_a, *_kw)
>   File "/odoo/odoo-server/openerp/http.py", line 810, in __call__
>     return self.method(_args, *_kw)
>   File "/odoo/odoo-server/openerp/http.py", line 410, in response_wrap
>     response = f(_args, *_kw)
>   File "/odoo/odoo-server/addons/web/controllers/main.py", line 948, in call_button
>     action = self._call_kw(model, method, args, {})
>   File "/odoo/odoo-server/addons/web/controllers/main.py", line 936, in _call_kw
>     return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
>   File "/odoo/odoo-server/openerp/api.py", line 268, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "/odoo/odoo-server/openerp/addons/base/module/module.py", line 447, in button_immediate_install
>     return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
>   File "/odoo/odoo-server/openerp/api.py", line 268, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "/odoo/odoo-server/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
>     registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
>   File "/odoo/odoo-server/openerp/modules/registry.py", line 370, in new
>     openerp.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/odoo/odoo-server/openerp/modules/loading.py", line 355, in load_modules
>     loaded_modules, update_module)
>   File "/odoo/odoo-server/openerp/modules/loading.py", line 255, in load_marked_modules
>     loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
>   File "/odoo/odoo-server/openerp/modules/loading.py", line 176, in load_module_graph
>     _load_data(cr, module_name, idref, mode, kind='data')
>   File "/odoo/odoo-server/openerp/modules/loading.py", line 118, in _load_data
>     tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
>   File "/odoo/odoo-server/openerp/tools/convert.py", line 900, in convert_file
>     convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
>   File "/odoo/odoo-server/openerp/tools/convert.py", line 977, in convert_xml_import
>     relaxng.assert_(doc)
>   File "src/lxml/lxml.etree.pyx", line 3501, in lxml.etree._Validator.assert_ (src/lxml/lxml.etree.c:194922)
> AssertionError: Expecting element openerp, got odoo, line 2

**Comment by ravindragullapalli** [comment]
This was happening because I was trying to configure the addon in odoo and not in open ERP. Closing it for now.
