### ISSUE TITLE
login failed error

### ISSUE THREAD

**Issue by dgimeno050** [WilldooIT/Pentaho-reports-for-OpenERP#288]
Hi
I am trying configure correctly the pentaho_reports module but I can't do it. 

The tomcat log says this:

```
 01, 2017 10:21:40 AM org.apache.xmlrpc.server.XmlRpcErrorLogger log
GRAVE: Failed to invoke method execute in class com.willowit.reporting.PentahoRenderer: Incorrect username and/or password.  Login Failed.
org.apache.xmlrpc.common.XmlRpcInvocationException: Failed to invoke method execute in class com.willowit.reporting.PentahoRenderer: Incorrect username and/or password.  Login Failed.
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:129)
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:106)
	at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:46)
	at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86)
	at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200)
	at org.apache.xmlrpc.webserver.XmlRpcServletServer.execute(XmlRpcServletServer.java:112)
	at org.apache.xmlrpc.webserver.XmlRpcServlet.doPost(XmlRpcServlet.java:196)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.willowit.application.PentahoResourceChecker.doFilter(PentahoResourceChecker.java:27)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:221)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.pentaho.reporting.engine.classic.core.ReportDataFactoryException: Incorrect username and/or password.  Login Failed.
	at org.pentaho.reporting.engine.classic.extensions.datasources.openerp.OpenERPDataFactory.queryData(OpenERPDataFactory.java:201)
	at org.pentaho.reporting.engine.classic.core.CompoundDataFactory.queryStaticInternal(CompoundDataFactory.java:205)
	at org.pentaho.reporting.engine.classic.core.CompoundDataFactory.queryStatic(CompoundDataFactory.java:182)
	at org.pentaho.reporting.engine.classic.core.cache.CachingDataFactory.queryInternal(CachingDataFactory.java:505)
	at org.pentaho.reporting.engine.classic.core.cache.CachingDataFactory.queryStatic(CachingDataFactory.java:181)
	at org.pentaho.reporting.engine.classic.core.CompoundDataFactory.queryStaticInternal(CompoundDataFactory.java:200)
	at org.pentaho.reporting.engine.classic.core.CompoundDataFactory.queryStatic(CompoundDataFactory.java:182)
	at org.pentaho.reporting.engine.classic.core.CompoundDataFactory.queryData(CompoundDataFactory.java:69)
	at org.pentaho.reporting.engine.classic.core.states.datarow.DefaultFlowController.performQueryData(DefaultFlowController.java:296)
	at org.pentaho.reporting.engine.classic.core.states.datarow.DefaultFlowController.performQuery(DefaultFlowController.java:217)
	at org.pentaho.reporting.engine.classic.core.states.process.ProcessState.initializeForMasterReport(ProcessState.java:331)
	at org.pentaho.reporting.engine.classic.core.layout.output.AbstractReportProcessor.prepareReportProcessing(AbstractReportProcessor.java:481)
	at org.pentaho.reporting.engine.classic.core.layout.output.AbstractReportProcessor.processReport(AbstractReportProcessor.java:1713)
	at org.pentaho.reporting.engine.classic.core.modules.output.pageable.pdf.PdfReportUtil.createPDF(PdfReportUtil.java:130)
	at com.willowit.reporting.PentahoRenderer.renderReport(PentahoRenderer.java:255)
	at com.willowit.reporting.PentahoRenderer.execute(PentahoRenderer.java:427)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:115)
	... 31 more
Caused by: java.lang.Exception: Incorrect username and/or password.  Login Failed.
	at com.debortoliwines.openerp.api.Session.startSession(Session.java:142)
	at com.debortoliwines.openerp.reporting.di.OpenERPHelper.getSession(OpenERPHelper.java:401)
	at com.debortoliwines.openerp.reporting.di.OpenERPHelper.getData(OpenERPHelper.java:86)
	at org.pentaho.reporting.engine.classic.extensions.datasources.openerp.OpenERPDataFactory.queryData(OpenERPDataFactory.java:197)
	... 51 more
Caused by:
org.pentaho.reporting.engine.classic.core.ReportDataFactoryException: Incorrect username and/or password.  Login Failed.
	at org.pentaho.reporting.engine.classic.extensions.datasources.openerp.OpenERPDataFactory.queryData(OpenERPDataFactory.java:201)
	at org.pentaho.reporting.engine.classic.core.CompoundDataFactory.queryStaticInternal(CompoundDataFactory.java:205)
	at org.pentaho.reporting.engine.classic.core.CompoundDataFactory.queryStatic(CompoundDataFactory.java:182)
	at org.pentaho.reporting.engine.classic.core.cache.CachingDataFactory.queryInternal(CachingDataFactory.java:505)
	at org.pentaho.reporting.engine.classic.core.cache.CachingDataFactory.queryStatic(CachingDataFactory.java:181)
	at org.pentaho.reporting.engine.classic.core.CompoundDataFactory.queryStaticInternal(CompoundDataFactory.java:200)
	at org.pentaho.reporting.engine.classic.core.CompoundDataFactory.queryStatic(CompoundDataFactory.java:182)
	at org.pentaho.reporting.engine.classic.core.CompoundDataFactory.queryData(CompoundDataFactory.java:69)
	at org.pentaho.reporting.engine.classic.core.states.datarow.DefaultFlowController.performQueryData(DefaultFlowController.java:296)
	at org.pentaho.reporting.engine.classic.core.states.datarow.DefaultFlowController.performQuery(DefaultFlowController.java:217)
	at org.pentaho.reporting.engine.classic.core.states.process.ProcessState.initializeForMasterReport(ProcessState.java:331)
	at org.pentaho.reporting.engine.classic.core.layout.output.AbstractReportProcessor.prepareReportProcessing(AbstractReportProcessor.java:481)
	at org.pentaho.reporting.engine.classic.core.layout.output.AbstractReportProcessor.processReport(AbstractReportProcessor.java:1713)
	at org.pentaho.reporting.engine.classic.core.modules.output.pageable.pdf.PdfReportUtil.createPDF(PdfReportUtil.java:130)
	at com.willowit.reporting.PentahoRenderer.renderReport(PentahoRenderer.java:255)
	at com.willowit.reporting.PentahoRenderer.execute(PentahoRenderer.java:427)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:115)
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:106)
	at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:46)
	at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86)
	at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200)
	at org.apache.xmlrpc.webserver.XmlRpcServletServer.execute(XmlRpcServletServer.java:112)
	at org.apache.xmlrpc.webserver.XmlRpcServlet.doPost(XmlRpcServlet.java:196)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.willowit.application.PentahoResourceChecker.doFilter(PentahoResourceChecker.java:27)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:221)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Incorrect username and/or password.  Login Failed.
	at com.debortoliwines.openerp.api.Session.startSession(Session.java:142)
	at com.debortoliwines.openerp.reporting.di.OpenERPHelper.getSession(OpenERPHelper.java:401)
	at com.debortoliwines.openerp.reporting.di.OpenERPHelper.getData(OpenERPHelper.java:86)
	at org.pentaho.reporting.engine.classic.extensions.datasources.openerp.OpenERPDataFactory.queryData(OpenERPDataFactory.java:197)
	... 51 more

```

and here is the odoo log

```
2017-02-01 09:50:30,847 1242 ERROR diolite8 openerp.service.report: Exception: <Fault 0: 'Failed to invoke method execute in class com.willowit.reporting.PentahoRenderer: Incorrect username and/or password.  Login Failed.'>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/service/report.py", line 93, in go
    result, format = openerp.report.render_report(cr, uid, ids, object, datas, context)
  File "/usr/lib/python2.7/dist-packages/openerp/report/__init__.py", line 40, in render_report
    return registry['ir.actions.report.xml'].render_report(cr, uid, ids, name, data, context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_actions.py", line 156, in render_report
    return new_report.create(cr, uid, res_ids, data, context)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/pentaho_reports/core.py", line 269, in create
    rendered_report, output_type = report_instance.execute()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/pentaho_reports/core.py", line 201, in execute
    return self.execute_report()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/pentaho_reports/core.py", line 239, in execute_report
    rendered_report = proxy.report.execute(proxy_argument).data
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
Fault: <Fault 0: 'Failed to invoke method execute in class com.willowit.reporting.PentahoRenderer: Incorrect username and/or password.  Login Failed.'>
2017-02-01 09:50:30,976 1242 ERROR diolite8 openerp.addons.web.controllers.main: An exception occured during an http request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 70, in wrap
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 1575, in index
    request.session.db, request.session.uid, request.session.password, report_id)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 886, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/usr/lib/python2.7/dist-packages/openerp/service/report.py", line 34, in dispatch
    res = fn(db, uid, *params)
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/base_report_to_printer/report_service.py", line 86, in exp_report_get
    return original_exp_report_get(db, uid, report_id)
  File "/usr/lib/python2.7/dist-packages/openerp/service/report.py", line 141, in exp_report_get
    return _check_report(report_id)
  File "/usr/lib/python2.7/dist-packages/openerp/service/report.py", line 119, in _check_report
    raise openerp.osv.orm.except_orm(exc.message, exc.traceback)
except_orm: ('', (<class 'xmlrpclib.Fault'>, <Fault 0: 'Failed to invoke method execute in class com.willowit.reporting.PentahoRenderer: Incorrect username and/or password.  Login Failed.'>, <traceback object at 0x7f9414041fc8>))
```

I see that says login is incorrect but I am trying to fix it some days and I can't fix the error.
I use in the pentaho system parameter user the same user that odoo uses. I can access to postgres database by local and remote hosts (I use pgadmin in my computer to access)

I tried to use with and without pentaho auth_crypt module.
I use the pentaho report designer 5.4

I need help to configure it because I need specific reports and I don't know use qweb language.

It's very posible that I need a very easy solution but I don't find it.

The characteristics of my installation are these:
- Ubuntu 16.04.1 LTS        4.4.0-59-generic
- Odoo Version 8.0-20170117(I installed Odoo by deb package)
- Apache Tomcat/7.0.68 (Ubuntu)
- JVM 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13
- Java server module builded in my machine and generated war file installed by tomcat manager (version 8.0.3)

Thanks you very much

**Comment by onduex** [comment]
Have you try with JDK 1.7??

**Comment by dgimeno050** [comment]
Hi onduex
I have just tried with jdk 1.7 from oracle but I have the same error

**Comment by dgimeno050** [comment]
Hi again. Now works correctly. I don't know exactly which modify in my server fixed the problem, but now works.
Thanks you very much for your spended time
