### ISSUE TITLE
When trying to install Pentaho addons in OpenERP v7 XML error

### ISSUE THREAD

**Issue by andreschenkels** [WilldooIT/Pentaho-reports-for-OpenERP#31]
2013-02-05 21:42:12,521 13688 ERROR erp7_pentahp openerp.addons.base.ir.ir_ui_view: Can't render view  for model: ir.actions.report.promptwizard
Traceback (most recent call last):
  File "/home/andre/workspace/git/erp7/server/openerp/addons/base/ir/ir_ui_view.py", line 125, in _check_render_view
    fvg = self.pool.get(view.model).fields_view_get(cr, uid, view_id=view.id, view_type=view.type, context=context)
  File "/home/andre/workspace/git/Pentaho-reports-for-OpenERP/openerp_addon/pentaho_reports/wizard/report_prompt.py", line 255, in fields_view_get
    self._setup_parameters(cr, uid, context=context)
  File "/home/andre/workspace/git/Pentaho-reports-for-OpenERP/openerp_addon/pentaho_reports/wizard/report_prompt.py", line 196, in _setup_parameters
    raise osv.except_osv(_('Error'), _("Invalid report associated with menu item."))
except_osv: (u'Error', u'Invalid report associated with menu item.')
2013-02-05 21:42:12,523 13688 ERROR erp7_pentahp openerp.tools.convert: Parse error in /home/andre/workspace/git/Pentaho-reports-for-OpenERP/openerp_addon/pentaho_reports/wizard/report_prompt.xml:4: 
<record model="ir.ui.view" id="wiz_pentaho_report_prompt">
            <field name="name">Pentaho Report Options</field>
            <field name="model">ir.actions.report.promptwizard</field>
            <field name="type">form</field>
            <field name="arch" type="xml">
                <form string="Pentaho Report Options">
                    <field name="report_name"/>
                    <newline/>
                    <field name="output_type" colspan="2"/>

```
                <!-- Place holder group for where selections will be inserted -->
                <group colspan="4" col="10" string="selections"/>

                <separator colspan="4"/>
                <group colspan="4" col="4">
                    <label string="" colspan="2"/>
                    <button icon="gtk-cancel" special="cancel" string="Cancel"/>
                    <button icon="gtk-print" name="check_report" string="Print" type="object"/>
                </group>
            </form>
        </field>
    </record>
```

Traceback (most recent call last):
  File "/home/andre/workspace/git/erp7/server/openerp/tools/convert.py", line 847, in parse
    self._tags[rec.tag](self.cr, rec, n)
  File "/home/andre/workspace/git/erp7/server/openerp/tools/convert.py", line 814, in _tag_record
    id = self.pool.get('ir.model.data')._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/andre/workspace/git/erp7/server/openerp/addons/base/ir/ir_model.py", line 956, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/andre/workspace/git/erp7/server/openerp/addons/base/ir/ir_ui_view.py", line 102, in create
    return super(osv.osv, self).create(cr, uid, values, context)
  File "/home/andre/workspace/git/erp7/server/openerp/osv/orm.py", line 4473, in create
    self._validate(cr, user, [id_new], context)
  File "/home/andre/workspace/git/erp7/server/openerp/osv/orm.py", line 1546, in _validate
    raise except_orm('ValidateError', '\n'.join(error_msgs))
except_orm: ('ValidateError', u'Error occurred while validating the field(s) arch: Invalid XML for View Architecture!')
2013-02-05 21:42:12,527 13688 ERROR erp7_pentahp openerp.netsvc: ValidateError
Error occurred while validating the field(s) arch: Invalid XML for View Architecture!
Traceback (most recent call last):
  File "/home/andre/workspace/git/erp7/server/openerp/netsvc.py", line 289, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/andre/workspace/git/erp7/server/openerp/service/web_services.py", line 614, in dispatch
    res = fn(db, uid, _params)
  File "/home/andre/workspace/git/erp7/server/openerp/osv/osv.py", line 169, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/home/andre/workspace/git/erp7/server/openerp/osv/osv.py", line 125, in wrapper
    raise except_osv(inst.name, inst.value)
except_osv: ('ValidateError', u'Error occurred while validating the field(s) arch: Invalid XML for View Architecture!')

**Comment by wenshan-willowit** [comment]
Hi André, could you please check whether you cloned branch "version70" (you can run  `$ git status` in the Pentaho directory) ?

If not, you can clone version70:

``` shell
$ git clone -b version70 git://github.com/WillowIT/Pentaho-reports-for-OpenERP.git
```

**Comment by andreschenkels** [comment]
Thank you. It works now. Very good work!

Sent from my Windows Phone

**Comment by sasaif** [comment]
Hi i have same problème as you on windows 7 and same log error , how i can fixe it please

**Comment by andreschenkels** [comment]
Okay,

Maybee you checked out the 6.1 version of the module and tried to install it on OpenERP version 7. You get an XML error when you do this.

Kind regards,

André Schenkels
ICTSTUDIO
mobiel | +31 6 53250063
email | a.schenkels@ictstudio.eumailto:a.schenkels@ictstudio.eu
[logo]

Van: sasaif [mailto:notifications@github.com]
Verzonden: maandag 16 september 2013 14:55
Aan: WillowIT/Pentaho-reports-for-OpenERP
CC: André Schenkels - ICTSTUDIO
Onderwerp: Re: [Pentaho-reports-for-OpenERP] When trying to install Pentaho addons in OpenERP v7 XML error (#31)

Hi i have same problème as you on windows 7 and same log error , how i can fixe it please

**Comment by sasaif** [comment]
thank you it work now

2013/9/16 André Schenkels notifications@github.com

**Comment by sasaif** [comment]
Hello
i made a pentaho report that work fine in the preview  with  paramatre
ect... but when i upload it on OPENERP v7 i got This Error

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30

OpenERP Server Error
Client Traceback (most recent call last):
  File "C:\Program Files\OpenERP
7.0\Server\server\openerp\addons\web\http.py", line 204, in dispatch
  File "C:\Program Files\OpenERP
7.0\Server\server\openerp\addons\web\controllers\main.py", line 1121,
in call_kw
  File "C:\Program Files\OpenERP
7.0\Server\server\openerp\addons\web\controllers\main.py", line 1113,
in _call_kw
  File "C:\Program Files\OpenERP
7.0\Server\server\openerp\addons\web\session.py", line 42, in proxy
  File "C:\Program Files\OpenERP
7.0\Server\server\openerp\addons\web\session.py", line 30, in
proxy_method
  File "C:\Program Files\OpenERP
7.0\Server\server\openerp\addons\web\session.py", line 103, in send

Server Traceback (most recent call last):
  File "C:\Program Files\OpenERP
7.0\Server\server\openerp\addons\web\session.py", line 89, in send
  File "C:\Program Files\OpenERP
7.0\Server\server.\openerp\netsvc.py", line 292, in dispatch_rpc
  File "C:\Program Files\OpenERP
7.0\Server\server.\openerp\service\web_services.py", line 626, in
dispatch
  File "C:\Program Files\OpenERP
7.0\Server\server.\openerp\osv\osv.py", line 188, in execute_kw
  File "C:\Program Files\OpenERP
7.0\Server\server.\openerp\osv\osv.py", line 131, in wrapper
  File "C:\Program Files\OpenERP
7.0\Server\server.\openerp\osv\osv.py", line 197, in execute
  File "C:\Program Files\OpenERP
7.0\Server\server.\openerp\osv\osv.py", line 185, in execute_cr
  File "C:\Program Files\OpenERP
7.0\Server\server\openerp\addons\pentaho_report\wizard\report_prompt.py",
line 263, in fields_view_get
  File "C:\Program Files\OpenERP
7.0\Server\server\openerp\addons\pentaho_report\wizard\report_prompt.py",
line 207, in _setup_parameters
  File "C:\Program Files\OpenERP 7.0\Server\server.\xmlrpclib.py",
line 986, in __call__
  File "C:\Program Files\OpenERP 7.0\Server\server.\xmlrpclib.py",
line 1239, in __request
  File "C:\Program Files\OpenERP 7.0\Server\server.\xmlrpclib.py",
line 1019, in request
  File "C:\Program Files\OpenERP 7.0\Server\server.\xmlrpclib.py",
line 1095, in send_content
  File "httplib.pyc", line 904, in endheaders
  File "httplib.pyc", line 776, in _send_output
  File "httplib.pyc", line 735, in send
  File "httplib.pyc", line 716, in connect
  File "socket.pyc", line 514, in create_connection
error: [Errno 10061] No connection could be made because the target
machine actively refused it

2013/9/16 ben salah ben unc.saif@gmail.com

**Comment by wenshan-willowit** [comment]
@sasaif 

It seems that your Pentaho server wasn't working properly. May I ask how you built and deployed the java servlet that is included in the repository? 

Also, you may want to check those Pentaho related configurations under Settings -> Technical -> Parameters -> System Parameters.

For example:
 pentaho.server.url -> http://localhost:8080/pentaho-reports-for-openerp
 pentaho.postgres.host -> localhost
 pentaho.postgres.port -> 5432

**Comment by sasaif** [comment]
i did make many simple report that work on OpenERP using Pentaho module and
my server work fine , it is juste i have a problem using Pentaho report
with Parametre , when i include it on OPENERP i have That Error alwyes
Appear .

2013/9/18 Ren Wenshan notifications@github.com

**Comment by sasaif** [comment]
i guess the probem is when i want to use SQL Query to make some condition
it doesnt work on OPENERP i got also this message
 Error

Pentaho returned no data for the report 'affiche'. Check report definition
and parameters.

2013/9/19 ben salah ben unc.saif@gmail.com

**Comment by sasaif** [comment]
i solve it Thank you Very much ,I fix it by properly configuring
Settings/Customization/System Parameters (pentaho.postgres.login and
pentaho.postgres.password); now my Pentaho reports are printing within
OpenERP as well.

2013/9/19 ben salah ben unc.saif@gmail.com
