### ISSUE TITLE
OpenERP 7 & netsvc issue

### ISSUE THREAD

**Issue by theopensourcerer** [WilldooIT/Pentaho-reports-for-OpenERP#36]
Hi, I've just done a bzr pull to update our development server's OpenERP 7 instance.

I'm then updating our databases from the command line with openerp-server -c myconfig-file -u all -d dbname and I started getting failures to complete the update in the Pentaho reports module.

the first I suspect is to do with Python paths Our system is laid out "/opt/openerp70/{addons, server, web}" but I seemed to fix by adding "from openerp" to the beginning of several import commands in core.py, ui.py & wizards/report_prompt.py.

Now I am seeing another error that looks to be more serious and I wonder if anyone can help?

2013-03-15 11:18:44,563 3324 ERROR MyDBName openerp: Failed to initialize database `MyDBName`.
Traceback (most recent call last):
  File "/opt/openerp70/server/openerp/cli/server.py", line 98, in preload_registry
    db, registry = openerp.pooler.get_db_and_pool(dbname,update_module=update_module)
  File "/opt/openerp70/server/openerp/pooler.py", line 33, in get_db_and_pool
    registry = RegistryManager.get(db_name, force_demo, status, update_module)
  File "/opt/openerp70/server/openerp/modules/registry.py", line 192, in get
    update_module)
  File "/opt/openerp70/server/openerp/modules/registry.py", line 228, in new
    registry.get('ir.actions.report.xml').register_all(cr)
  File "/opt/openerp70/addons/pentaho_reports/core.py", line 198, in register_all
    register_pentaho_report(record["report_name"])
  File "/opt/openerp70/addons/pentaho_reports/core.py", line 166, in register_pentaho_report
    if name in netsvc.Service._services:
AttributeError: 'module' object has no attribute 'Service'

**Comment by theopensourcerer** [comment]
I just did a grep and in OpenERP 7, netsvc.py does not have the string "Service" in it anywhere, whereas in OpenERP 6.1 there is a class "Service" in netsvc.py so it looks like this may have been removed...

**Comment by theopensourcerer** [comment]
Ahh, really sorry - think this was my bad. My OpenERP "7" dev server is actually pulling from trunk! the class "Service" is still in the 7.0 branch. 

Sorry for the noise.
