### ISSUE TITLE
Images no more shown in report

### ISSUE THREAD

**Issue by flotho** [WilldooIT/Pentaho-reports-for-OpenERP#81]
Hy,

I upddated to the latest revision for openerp 7.0.
I made a new war wiyj all dependencies and redeploy it.
I uppdated the openerp module

I use one of your tip for displaying images and it works correctly in the PRD.
Unfortunatley, when I deploy it on the OpenERP, images are not shown anymore. It was working on the PRD3.9 with your tips.
Is there any dependencies unmatched?

regards

**Comment by flotho** [comment]
Is there any possible reason for this?
Do I have to redeploy the war, reinstall the module or changing something in my query would be enough?

**Comment by flotho** [comment]
could it come from the fact that the server is 4.8 and the module designed for the 5.0 sever

**Comment by richard-willdooit** [comment]
Sorry, I have not had a chance to look at this yet.  Could you check the dependencies by manually copying the libraries from the report designer lib folder to the one that tomcat would use.

Also, could you tell me what is happening in catalina.out

**Comment by flotho** [comment]
Sure, I'll try this for you soon.

**Comment by flotho** [comment]
Hy,

So here is what I've done : 
- Clone the latest branch 70
- Reinstall the latest IVY/ANT binaries
- Generate a new .war for the java server
- Deploy this .war in tomcat
- Create a new report in 5.0.1 report designer
- Set it in OpenERP
- Use your tip here to display image https://github.com/WillowIT/Pentaho-reports-for-OpenERP/wiki/Displaying-images-for-SQL-Reports
- Check directly from pentaho report designer that the report is correctly displaying images :  Ok!
- run the report form OpenERP => No images are displayed
  Here is the logs in catalina : 

``` java
[WARN] ContentType - Failed to load content using value [B@11eeb964 <org.pentaho.reporting.libraries.resourceloader.ContentNotRecognizedException: None of the selected factories was able to handle the given data: ResourceKey{schema=org.pentaho.reporting.libraries.resourceloader.loader.raw.RawResourceLoader, identifier=[B@11eeb964, factoryParameters={}, parent=null}>org.pentaho.reporting.libraries.resourceloader.ContentNotRecognizedException: None of the selected factories was able to handle the given data: ResourceKey{schema=org.pentaho.reporting.libraries.resourceloader.loader.raw.RawResourceLoader, identifier=[B@11eeb964, factoryParameters={}, parent=null}
        at org.pentaho.reporting.libraries.resourceloader.DefaultResourceManagerBackend.create(DefaultResourceManagerBackend.java:295)
        at org.pentaho.reporting.libraries.docbundle.BundleResourceManagerBackend.create(BundleResourceManagerBackend.java:168)
        at org.pentaho.reporting.libraries.resourceloader.ResourceManager.create(ResourceManager.java:442)
        at org.pentaho.reporting.engine.classic.core.filter.types.ContentType.filter(ContentType.java:207)
        at org.pentaho.reporting.engine.classic.core.filter.types.ContentFieldType.getValue(ContentFieldType.java:68)
        at org.pentaho.reporting.engine.classic.core.layout.build.DefaultLayoutBuilderStrategy.computeValue(DefaultLayoutBuilderStrategy.java:297)
        at org.pentaho.reporting.engine.classic.core.layout.build.DefaultLayoutBuilderStrategy.processContent(DefaultLayoutBuilderStrategy.java:229)
        at org.pentaho.reporting.engine.classic.core.layout.build.DefaultLayoutBuilderStrategy.addBandInternal(DefaultLayoutBuilderStrategy.java:162)
        at org.pentaho.reporting.engine.classic.core.layout.build.DefaultLayoutBuilderStrategy.addBandInternal(DefaultLayoutBuilderStrategy.java:158)
        at org.pentaho.reporting.engine.classic.core.layout.build.DefaultLayoutBuilderStrategy.addBandInternal(DefaultLayoutBuilderStrategy.java:158)
        at org.pentaho.reporting.engine.classic.core.layout.build.DefaultLayoutBuilderStrategy.add(DefaultLayoutBuilderStrategy.java:112)
        at org.pentaho.reporting.engine.classic.core.layout.build.ReportRenderModelBuilder.add(ReportRenderModelBuilder.java:191)
        at org.pentaho.reporting.engine.classic.core.layout.AbstractRenderer.add(AbstractRenderer.java:359)
        at org.pentaho.reporting.engine.classic.core.layout.output.DefaultOutputFunction.print(DefaultOutputFunction.java:1338)
        at org.pentaho.reporting.engine.classic.core.layout.output.DefaultOutputFunction.updatePageFooter(DefaultOutputFunction.java:917)
        at org.pentaho.reporting.engine.classic.core.layout.output.DefaultOutputFunction.updateFooterArea(DefaultOutputFunction.java:870)
        at org.pentaho.reporting.engine.classic.core.layout.output.DefaultOutputFunction.reportStarted(DefaultOutputFunction.java:177)
        at org.pentaho.reporting.engine.classic.core.states.datarow.ExpressionEventHelper.fireReportStartedEvent(ExpressionEventHelper.java:481)
        at org.pentaho.reporting.engine.classic.core.states.datarow.ExpressionEventHelper.fireReportEvent(ExpressionEventHelper.java:91)
        at org.pentaho.reporting.engine.classic.core.states.InitialLayoutProcess.fireReportEvent(InitialLayoutProcess.java:190)
        at org.pentaho.reporting.engine.classic.core.states.SubLayoutProcess.fireReportEvent(SubLayoutProcess.java:217)
        at org.pentaho.reporting.engine.classic.core.states.process.ProcessState.fireReportEvent(ProcessState.java:1285)
        at org.pentaho.reporting.engine.classic.core.states.process.ReportHeaderHandler.advance(ReportHeaderHandler.java:47)
        at org.pentaho.reporting.engine.classic.core.states.process.ProcessState.advance(ProcessState.java:1076)
        at org.pentaho.reporting.engine.classic.core.layout.output.AbstractReportProcessor.processPage(AbstractReportProcessor.java:1287)
        at org.pentaho.reporting.engine.classic.core.layout.output.AbstractReportProcessor.processReport(AbstractReportProcessor.java:1685)
        at org.pentaho.reporting.engine.classic.core.modules.output.pageable.pdf.PdfReportUtil.createPDF(PdfReportUtil.java:130)
        at com.willowit.reporting.PentahoRenderer.renderReport(Unknown Source)
        at com.willowit.reporting.PentahoRenderer.execute(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:115)
        at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:106)
        at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:46)
        at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86)
        at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200)
        at org.apache.xmlrpc.webserver.XmlRpcServletServer.execute(XmlRpcServletServer.java:112)
        at org.apache.xmlrpc.webserver.XmlRpcServlet.doPost(XmlRpcServlet.java:196)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.willowit.application.PentahoResourceChecker.doFilter(Unknown Source)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:724)
```

In the IVY process, I've seen that you downloaded TRUNK SNAPSHOST for some jar.
Isn't it a dangerous way since we have now a stable build?

Hope it can help, regards

**Comment by flotho** [comment]
I updated all the libs with those in the pentaho report designer and it works.
The release I use for pentaho report designer is : http://sourceforge.net/projects/jfreereport/files/04.%20Report%20Designer/5.0.1-stable/prd-ce-5.0.1-stable.zip/download

regards

**Comment by flotho** [comment]
Hy,

So you meant that pulling git plus rebuilding the server will be enough to solved 2 issues at a time?

**Comment by pietercvdm** [comment]
Hi flotho

You seem to be a big user of Pentaho.  I've also fixed some issues you reported on kettle?  Good to see people using the tools.

WillowIT haven't merged the pull request in from my branch.  A git pull will not fix it at the moment, but hopefully it does after they merge it.

For now, could you please test if my branch fixes your issue?  Try 
- git clone https://github.com/pietercvdm/Pentaho-reports-for-OpenERP.git
- cd Pentaho-reports-for-OpenERP/java_server
- git checkout version70
- ant war

Dependencies on my branch have been updated as per Pentaho's suggestion and hopefully it resolves your image issues.

After testing you should go back to WillowIT's code since I don't always keep my branch up to date.

Kind Regards,
Pieter

**Comment by flotho** [comment]
Hy,

The problem regarding to the PDF compatibility seems to be solved.
Unfortunately, the image issue is not corrected.
Still have :
ailed to load content using value [B@7d534e34
org.pentaho.reporting.libraries.resourceloader.ContentNotRecognizedException: None of the selected factories was able to handle the given data: ResourceKey{schema=org.pentaho.reporting.libraries.resourceloader.loader.raw.RawResourceLoader, identifier=[B@7d32c6a8, factoryParameters={}, parent=null}
        at org.pentaho.reporting.libraries.resourceloader.DefaultResourceManagerBackend.create(DefaultResourceManagerBackend.java:294)
        at org.pentaho.reporting.libraries.docbundle.BundleResourceManagerBackend.create(BundleResourceManagerBackend.java:165)
        at org.pentaho.reporting.libraries.resourceloader.ResourceManager.create(ResourceManager.java:434)
        at org.pentaho.reporting.engine.classic.core.filter.types.ContentType.filter(ContentType.java:246)

**Comment by flotho** [comment]
Pieter,

I made a mistake I forgot to make a cheeckout.
Unfortunately I have this message while building war :
  [javac] /home/florent/DEV/Serveurs/openerp-7.0-series/pentaho_report_fix/java_server/build-res/subfloor.xml:1160: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 4 source files to /home/florent/DEV/Serveurs/openerp-7.0-series/pentaho_report_fix/java_server/bin/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] /home/florent/DEV/Serveurs/openerp-7.0-series/pentaho_report_fix/java_server/src/com/willowit/application/PentahoResourceChecker.java:5: error: package javax.servlet does not exist
    [javac] import javax.servlet.Filter;
    [javac]                     ^
    [javac] /home/florent/DEV/Serveurs/openerp-7.0-series/pentaho_report_fix/java_server/src/com/willowit/application/PentahoResourceChecker.java:6: error: package javax.servlet does not exist
    [javac] import javax.servlet.FilterChain;
    [javac]                     ^
    [javac] /home/florent/DEV/Serveurs/openerp-7.0-series/pentaho_report_fix/java_server/src/com/willowit/application/PentahoResourceChecker.java:7: error: package javax.servlet does not exist
    [javac] import javax.servlet.FilterConfig;
    [javac]                     ^
    [javac] /home/florent/DEV/Serveurs/openerp-7.0-series/pentaho_report_fix/java_server/src/com/willowit/application/PentahoResourceChecker.java:8: error: package javax.servlet does not exist
    [javac] import javax.servlet.ServletException;

**Comment by pietercvdm** [comment]
The dependencies do not resolve by default using the 'ant war' command.

You've got two options.
1.  Resolve it manually.  'ant resolve'; and then 'ant war'.
2.  Or use the default run target that does everything ant'.

I've updated the readme to reflect the recent changes (to just run 'ant').

Thanks for testing.

**Comment by flotho** [comment]
Hy it corrects the problem regarding to the pdf format but images are not displayed anymore.

**Comment by pietercvdm** [comment]
Hi Flotho

I was hoping that moving to Pentaho's suggested build would fix it but it seems I have more testing to do.

I am swamped at the moment and will hopefully get back to this issue some time next week.

Thanks for your patience.

Kind Regards,
Pieter

**Comment by thomas-willdooit** [comment]
Hello Flotho,
Have you downloaded the pre-built war file from [Here](http://cloud1.willowit.com.au/dist/pentaho-reports-for-openerp.war)?

**Comment by flotho** [comment]
Hy,

I tried with your .war. There is no more problems for the format but images are no more displayed

**Comment by flotho** [comment]
Hy,

I replace some libs from your install by one of mine DL from ci.pentaho.com and it works. Obviously, one of the jar wasn't up to date.

**Comment by flotho** [comment]
Or maybe that was coming from the jdbc that wasn't in the correct version

**Comment by richard-willdooit** [comment]
Hi,

We are going to close this now.  We believe that the issues are resolved in the latest.

Richard

**Comment by pietercvdm** [comment]
Hi Richard / Thomas

This bug was reported again.  It may be related to the version of PostgreSQL that is in use.  I could recreate the bug using PostgreSQL 9.1.  Updating the PostgreSQL driver to the same version as the designer (9.1-902.jdbc4) seems to fix the issue.  The original driver returns a value/datatype that is not correctly detected by Pentaho 5.0.

Please test to check that I haven't broken your deployment and merge if you are happy.

flotho please give it a test too if you are still having issues (from my repository [here](https://github.com/pietercvdm/Pentaho-reports-for-OpenERP)).

Thanks,
Pieter

**Comment by richard-willdooit** [comment]
Thanks Pieter,

Will test this afternoon.

Richard

**Comment by richard-willdooit** [comment]
Pieter and others following this,

Sorry, I forgot to comment here.  The latest changes have rectified the image print problem, and the pre-built war file on willowit.com.au has been updated accordingly.

Richard

**Comment by pietercvdm** [comment]
Great.  Happy this bug finally got resolved.

Thanks for the feedback.
